# we will use node:latest docker image
FROM node:latest

# set /app as work directory
WORKDIR /app

# copy package.json to work directory, so that we install npm dependencies
COPY package*.json /app
COPY yarn.lock /app

# install npm dependencies
RUN yarn install

# copy your project files to work directory
COPY . /app

# run your app
CMD ["yarn", "run", "start-dev"]